name: WokePlugin
description: Adds user-defined nicknames and pronouns. Overrides default chat renderer.
version: 1.0-SNAPSHOT
main: net.maxmushroom.wokeplugin.WokePlugin
api-version: '1.21.4'

commands:
   pronouns:
      description: Manage your pronouns.
      usage: "Usage: /pronouns <set|clear>"
   nickname:
      description: Manage your nickname.
      usage: "Usage: /nickname <set|clear>"
      aliases: [nick]