name: WokePlugin
description: Adds user-defined nicknames and pronouns. Overrides default chat renderer.
version: 0.1.1
main: net.maxmushroom.wokeplugin.WokePlugin
api-version: '1.21.4'

commands:
   pronouns:
      description: Manage your pronouns.
      usage: "§cUsage: /pronouns <set | clear>"
   nickname:
      description: Manage your nickname.
      usage: "§cUsage: /nickname <set | clear>"
      aliases: [nick]